---
name: Continuous Integration
on:
  push:
    - main 
#  workflow_dispatch:
jobs:
  build:
    name: print
    runs-on: ubuntu-latest
    steps:
      - name: print workflow name
        run: echo "first workflow"
