---
name: Continuous Integration
on:
  workflow_dispatch:
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v3.1.0
      - name: Lint
        uses: github/super-linter/slim@v4.9.7
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          VALIDATE_GO: false
          VALIDATE_ALL_CODEBASE: false
